const dataSelection = [
  {
    name: "",
    id: "",
    img: "./src/assets/img/PicturesBlink.png",
    isHidden: true,
  },
  {
    name: "Batman",
    id: 70,
    img: "./src/assets/img/PicturesGood-Batman.png",
    isHidden: false,
  },
  {
    name: "Balck Panther",
    id: 106,
    img: "./src/assets/img/PicturesGood-BlackPanther.png",
    isHidden: false,
  },
  {
    name: "Black Widow",
    id: 107,
    img: "./src/assets/img/PicturesGood-BlackWidow.png",
    isHidden: false,
  },
  {
    name: "Bane",
    id: 60,
    img: "./src/assets/img/PicturesBad-Bane.png",
    isHidden: false,
  },
  {
    name: "Black Adam",
    id: 95,
    img: "./src/assets/img/PicturesBad-BlackAdam.png",
    isHidden: false,
  },
  {
    name: "Carnage",
    id: 162,
    img: "./src/assets/img/PicturesBad-Carnage.png",
    isHidden: false,
  },
  {
    name: "",
    id: "",
    img: "./src/assets/img/PicturesBlink.png",
    isHidden: true,
  },
  {
    name: "Captain America",
    id: 149,
    img: "./src/assets/img/PicturesGood-CaptainAmerica.png",
    isHidden: false,
  },
  {
    name: "Captain Marvel",
    id: 157,
    img: "./src/assets/img/PicturesGood-CaptainMarvel.png",
    isHidden: false,
  },
  {
    name: "Cyclops",
    id: 196,
    img: "./src/assets/img/PicturesGood-Cyclops.png",
    isHidden: false,
  },
  {
    name: "Deadpool",
    id: 213,
    img: "./src/assets/img/PicturesGood-Deadpool.png",
    isHidden: false,
  },
  {
    name: "Darkseid",
    id: 204,
    img: "./src/assets/img/PicturesBad-Darkseid.png",
    isHidden: false,
  },
  {
    name: "Doomsday",
    id: 230,
    img: "./src/assets/img/PicturesBad-Doomsday.png",
    isHidden: false,
  },
  {
    name: "Harley Quinn",
    id: 309,
    img: "./src/assets/img/PicturesBad-HarleyQuinn.png",
    isHidden: false,
  },
  {
    name: "Joker",
    id: 370,
    img: "./src/assets/img/PicturesBad-Joker.png",
    isHidden: false,
  },
  {
    name: "Hellrider",
    id: 280,
    img: "./src/assets/img/PicturesGood-Hellrider.png",
    isHidden: false,
  },
  {
    name: "Ironman",
    id: 346,
    img: "./src/assets/img/PicturesGood-Ironman.png",
    isHidden: false,
  },
  {
    name: "Spiderman",
    id: 620,
    img: "./src/assets/img/PicturesGood-Spiderman.png",
    isHidden: false,
  },
  {
    name: "Superman",
    id: 644,
    img: "./src/assets/img/PicturesGood-Superman.png",
    isHidden: false,
  },
  {
    name: "Lex Luthor",
    id: 405,
    img: "./src/assets/img/PicturesBad-LexLuthor.png",
    isHidden: false,
  },
  {
    name: "Loki",
    id: 414,
    img: "./src/assets/img/PicturesBad-Loki.png",
    isHidden: false,
  },
  {
    name: "Magneto",
    id: 423,
    img: "./src/assets/img/PicturesBad-Magneto.png",
    isHidden: false,
  },
  {
    name: "Mister Sinister",
    id: 460,
    img: "./src/assets/img/PicturesBad-MisterSinister.png",
    isHidden: false,
  },
  {
    name: "",
    id: "",
    img: "./src/assets/img/PicturesBlink.png",
    isHidden: true,
  },
  {
    name: "Thor",
    id: 659,
    img: "./src/assets/img/PicturesGood-Thor.png",
    isHidden: false,
  },
  {
    name: "Wolverine",
    id: 717,
    img: "./src/assets/img/PicturesGood-Wolverine.png",
    isHidden: false,
  },
  {
    name: "Wonderwoman",
    id: 720,
    img: "./src/assets/img/PicturesGood-Wonderwoman.png",
    isHidden: false,
  },
  {
    name: "Modok",
    id: 463,
    img: "./src/assets/img/PicturesBad-Modok.png",
    isHidden: false,
  },
  {
    name: "Poison Ivy",
    id: 522,
    img: "./src/assets/img/PicturesBad-PoisonIvy.png",
    isHidden: false,
  },
  {
    name: "Thanos",
    id: 655,
    img: "./src/assets/img/PicturesBad-Thanos.png",
    isHidden: false,
  },
  {
    name: "",
    id: "",
    img: "./src/assets/img/PicturesBlink.png",
    isHidden: true,
  },
];

export default dataSelection;
